# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html#core-section
[core]
reloadable = true
order = 0

# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html#package-section
[package]
version = "0.1.0"
category = "<EXT_CATEGORY>"
title = "<EXT_TITLE>"
description = "<EXT_DESCRIPTION>"
authors = ["<EXT_AUTHORS>"]
repository = "<EXT_REPOSITORY>"
keywords = ["<EXT_KEYWORDS>"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html#dependencies-section
[dependencies]

# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html#python-section
[[python.module]]
name = "<EXT_NAME>"

# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html#settings-section
[settings]
